### ISSUE TITLE
Export PDF des talks pour le programme

### ISSUE THREAD

**Issue by alexthomazo** [breizhcamp/konter#5]
Pouvoir exporter les talks au format PDF qui nous permet de constituer le programme.

Chaque talk est exporté dans une petite carte avec un code barre.

Un exemple de code est fourni dans cette issue.
[pdf-cfp-cards.zip](https://github.com/breizhcamp/konter/files/14761764/pdf-cfp-cards.zip)

**Comment by claire-lucas** [comment]
Ajouté dans [ce commit](https://github.com/breizhcamp/konter/commit/5d4e3c97fedb80cbb0eaa8289a53b1a8ce76e556)
